@env = http://localhost:8890

### Create
PUT {{env}}/product
Content-Type: application/json

{
  "id": "demoId",
  "name": "demoProduct",
  "enabled": true 
}

### Single Query
GET {{env}}/product/demoId

### Update
PATCH {{env}}/product/demoId
Content-Type: application/json

{
  "name": "updated",
  "enabled": false
}

### Query
POST {{env}}/product
Content-Type: application/json

{
  "pos": 0,
  "limit": 5
}

### Delete
DELETE {{env}}/product/demoId

### Batch Delete
DELETE {{env}}/product
Connection: application/json

["1", "2", "3", "demoId"]
