@env = http://localhost:8890

### Create
PUT {{env}}/user
Content-Type: application/json

{
  "name": "user",
  "age": 11
}

### Update
PATCH {{env}}/user/1
Content-Type: application/json

{
  "name": "updated",
  "enabled": false
}

### Query
POST {{env}}/user
Content-Type: application/json

{
  "pos": 0,
  "limit": 5
}

### Delete
DELETE {{env}}/user/1

### Batch Delete
POST {{env}}/user/batch
Connection: application/json

["1", "2", "3", "demoId"]
